/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sporsalonu;

/**
 *
 * @author hp
 */
public class Programlar extends javax.swing.JFrame {

    /** Creates new form Programlar */
    public Programlar() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel70 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Programlar");

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Çıkış");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("1. Program");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel6.setText("Overhead Press 3x5");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel7.setText("Squat 3x5");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel8.setText("Squat Asistanı 3x8-12");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 10));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel9.setText("Bench Press 3x5");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel10.setText("Bench Press Asistanı 3x8-12");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel11.setText("Pendlay Row 3x5");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel12.setText("Row Asistanı 3x8-12");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel13.setText("Ağırlık Plank");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel14.setText("Front Squat 3x5");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel15.setText("Ağırlık Plank");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, -1));

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel16.setText("Squat Asistanı 3x8-12");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel17.setText("Overhead Press Asistanı 3x8-12");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        jLabel18.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel18.setText("Bench Press Asistanı 3x8-12");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        jLabel19.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel19.setText("Deadlift 1x5");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        jLabel20.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel20.setText("Deadlift 3x5-12");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        jLabel21.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel21.setText("Ağırlık Plank");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        jLabel22.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel22.setText("Squat 3x5");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));

        jLabel23.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel23.setText("Squat Asistanı 3x8-12");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, -1));

        jLabel24.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel24.setText("Bench Press 3x5");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        jLabel25.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel25.setText("Bench Press Asistanı 3x8-12");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        jLabel26.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel26.setText("Pendlay Row 3x5");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        jLabel27.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel27.setText("Row Asistanı 3x8-12");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sporsalonu/be989cda0e5236d62efcd774032ea319.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 270));

        jTabbedPane1.addTab("1 Program", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel29.setText("RPE 7-8-9, 3'-5' dinlenme");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jButton2.setText("Çıkış");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel28.setText("2. Program");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel30.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel30.setText("RPE 6-7-8, 2'-3' dinlenme");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

        jLabel31.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel31.setText("Paused Bench Press 3x5");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel32.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel32.setText("Overhead Press 3x8");
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel33.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel33.setText("Facepull 3x20");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel34.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel34.setText("Paused Deadlift 3x5");
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel35.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel35.setText("Power Shrug 3x5");
        jPanel3.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel36.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel36.setText("Rack Pull 3x10");
        jPanel3.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel37.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel37.setText("Hammer Curl 3x10");
        jPanel3.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel38.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel38.setText("Squat 3x5");
        jPanel3.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel39.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel39.setText("Seçmeli Row 3x10");
        jPanel3.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, -1));

        jLabel40.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel40.setText("Romenian Deaflift 3x10");
        jPanel3.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        jLabel41.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel41.setText("Seçmeli Press 3x10");
        jPanel3.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, -1));

        jLabel42.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel42.setText("Z Press 3x10");
        jPanel3.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        jLabel43.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel43.setText("Şınav 3xmax");
        jPanel3.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        jLabel44.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel44.setText("Facepull 3x20");
        jPanel3.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        jLabel45.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel45.setText("Pulldown 4x10");
        jPanel3.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        jLabel46.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel46.setText("Seçmeli Row 3x10");
        jPanel3.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));

        jLabel47.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel47.setText("Squat 3x15");
        jPanel3.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        jLabel48.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel48.setText("Hip Thrust 3x10");
        jPanel3.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        jLabel49.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel49.setText("Leg Extension 3x10");
        jPanel3.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        jLabel50.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel50.setText("Leg Curl 3x10");
        jPanel3.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, -1));

        jLabel51.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel51.setText("Seçmeli Press 3x5");
        jPanel3.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, -1));

        jLabel52.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel52.setText("Side Raise 3x10");
        jPanel3.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        jLabel53.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel53.setText("Facepull 3x20");
        jPanel3.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));

        jLabel55.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel55.setText("RPE 7-8-9, 3'-4' dinlenme");
        jPanel3.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, -1));

        jLabel54.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel54.setText("Pulldown 3x10");
        jPanel3.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sporsalonu/be989cda0e5236d62efcd774032ea319.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 260));

        jTabbedPane1.addTab("2.Program", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("Çıkış");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel56.setText("3. Program");
        jPanel4.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel57.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel57.setText("Biceps 1-2x12-15/1.5'");
        jPanel4.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        jLabel58.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel58.setText("Squat 3-4x6-8/3' dk dinlenme");
        jPanel4.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel59.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel59.setText("Stiff leg 3-4x6-8/3'");
        jPanel4.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel60.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel60.setText("Leg Press 2-3x10-12/2'");
        jPanel4.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel61.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel61.setText("Leg Curl 2-3x10-12/2'");
        jPanel4.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel62.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel62.setText("Curl Raise 3-4x6-8/3'");
        jPanel4.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel63.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel63.setText("Deadlift 2-3x10-12/2'");
        jPanel4.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel64.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel64.setText("Bench Press 3-4x6-8/3'");
        jPanel4.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        jLabel65.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel65.setText("Seçmeli Row 3-4x6-8/3'");
        jPanel4.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        jLabel66.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel66.setText("Incline Bench Press 2-3x10-12/2'");
        jPanel4.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        jLabel67.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel67.setText("Barfiks 2-3x10-12/2'");
        jPanel4.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        jLabel68.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel68.setText("Triceps 1-2x12-15/1.5'");
        jPanel4.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sporsalonu/be989cda0e5236d62efcd774032ea319.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 260));

        jTabbedPane1.addTab("3.Program", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setText("Çıkış");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        jLabel70.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel70.setText("Lat Pulldown 2x10");
        jPanel5.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel69.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel69.setText("4. Program");
        jPanel5.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel71.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel71.setText("Seated Row Makinesi 2x10");
        jPanel5.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        jLabel72.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel72.setText("Goblet Squat 3x12");
        jPanel5.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel73.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel73.setText("Rommanian Deadlift 2x15");
        jPanel5.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel74.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel74.setText("Prone Cobra 2x10");
        jPanel5.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel75.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel75.setText("Hip Abduction 2x20");
        jPanel5.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel76.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel76.setText("Incline Press 2x10");
        jPanel5.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel77.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel77.setText("Hip Thrust 4x6");
        jPanel5.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel78.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel78.setText("Overhead Press 2x10");
        jPanel5.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, -1));

        jLabel79.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel79.setText("Bulgarian Split Squat 2x10");
        jPanel5.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        jLabel80.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel80.setText("Glute Kickback 3x10");
        jPanel5.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        jLabel81.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel81.setText("Kettlebell Swing 2x30 saniye");
        jPanel5.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        jLabel82.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel82.setText("Plank 2x90 saniye");
        jPanel5.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        jLabel83.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel83.setText("Leg Rise 3x10");
        jPanel5.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        jLabel84.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel84.setText("Push Up 2xmax tekrar");
        jPanel5.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        jLabel85.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel85.setText("Hip Thrust 3x10");
        jPanel5.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        jLabel86.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel86.setText("Hip Thrust 3x20");
        jPanel5.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));

        jLabel87.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel87.setText("Leg Press 3x10");
        jPanel5.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, -1));

        jLabel88.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel88.setText("Rommanian Deadlift 2x8");
        jPanel5.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        jLabel89.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel89.setText("Hip Abduction 2x20");
        jPanel5.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        jLabel90.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel90.setText("Dambıl Bench Press 2x15");
        jPanel5.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        jLabel91.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        jLabel91.setText("Inverted Row 2x10");
        jPanel5.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sporsalonu/be989cda0e5236d62efcd774032ea319.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 260));

        jTabbedPane1.addTab("4.Program", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(579, 321));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.hide();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.hide();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Programlar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Programlar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Programlar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Programlar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Programlar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

}
